name: Automerge PR to Nonprod
on:
  pull_request:
    branches:
        - nonprod
jobs:
    run-unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python 3.10.4
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.4
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Start mongodb
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                mongodb_version: ${{ matrix.mongodb_version }}
            - name: Run unit tests
              run: |
                pytest
    automerge-dependabot:
        name: Automerge Dependabot PR
        needs: run-unit-test

        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Merge PR
              uses: fastify/github-action-merge-dependabot@v3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                merge-method: rebase
                target: minor
            