name: Create Pull Request for develop to nonprod branch
on:
  push:
    branches:
      - develop

jobs:
    create_pr:
        runs-on: ubuntu-latest
        steps:
            - name: Pull Request Action
              uses: vsoch/pull-request-action@master
              with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: develop
                    title: Create Pull Request for develop to nonprod branch
                    body: |
                        This is an automated pull request to merge develop into nonprod
                    labels: |
                        - automerge                  
            
