name: Create Pull Request for develop to nonprod branch
on:
  push:
    branches:
      - develop

jobs:
    create_pr:
        runs-on: ubuntu-latest
        steps:
            - name: Pull Request Action
              uses: vsoch/pull-request-action@master
              env: 
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GITHUB_REPOSITORY: ${{ github.repository }}
                    GITHUB_ACTOR: ${{ github.actor }}
                    GITHUB_REF: ${{ github.ref }}
                    GITHUB_SHA: ${{ github.sha }}
                    GITHUB_EVENT_NAME: ${{ github.event_name }}
                    GITHUB_EVENT_PATH: ${{ github.event_path }}
                    GITHUB_WORKSPACE: ${{ github.workspace }}
                    GITHUB_HEAD_REF: develop
                    GITHUB_BASE_REF: nonprod  
                    BRANCH_PREFIX: "develop"
                    PR_TITLE: "Create Pull Request for develop to nonprod branch"
                    PULL_REQUEST_BRANCH: "nonprod"             
            
