# when code is pushed to develop branch create a new Pull Request to nonprod branch

name: Create PR to nonprod branch

on:
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: create PR to nonprod branch'
          title: 'chore: create PR to nonprod branch'
          body: 'This PR is created automatically when code is pushed to develop branch'
          branch: nonprod
          base: main
          labels: 'automated-pr'
