#  I want to run the tests when I create a new PR to make sure that the code is working as expected.
# once the test is successul merge the develop branch to nonprod branch
# also spin up the mongodb docker as it is used to connect to it
# docker run --name mongodb -p 27017:27017 -v ./data:/data/db -d mongodb/mongodb-enterprise-server:latest
name: CI

on:
  push:
    branches:
      - develop

jobs: 
    test_schedule: 
        runs-on: ubuntu-latest
        steps:
            - name: Pull Request Action
              uses: vsoch/pull-request-action@master
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH_PREFIX: "develop"
                PULL_REQUEST_BRANCH: "nonprod"
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python 3.10.4
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.4
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Start mongodb
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                mongodb_version: ${{ matrix.mongodb_version }}
            - name: Run tests
              run: |
                pytest
              # if tests pass, merge develop to nonprod
            - name: Merge develop to nonprod
              if: success()
              uses: actions/checkout@v3
              with:
                ref: nonprod
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Merge Development branch into Non-Production
              run: |
                git merge origin/develop --allow-unrelated-histories
                git push origin nonprod



              

      
